### PR TITLE
improving links

### PR DESCRIPTION
**Pull request by haouarihk**

### CODE REVIEW

**Comment by haouarihk** [comment]
you need to put my releases page in your releases page
with the same tag

**Comment by haouarihk** [comment]
here is the release
https://github.com/haouarihk/Port-Windows-11-Poco-X3-pro/releases/tag/binaries

**Comment by halal-beef** [comment]
Degdag doesn't release efi via releases

**Comment by halal-beef** [comment]
Nvm he does, sorry but it seems to 404

**Comment by halal-beef** [comment]
Remove /tag

**Pull request merged**
